apiVersion: v1
kind: Template
metadata:
  name: topological-inventory-ingress-api
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: topological-inventory-ingress-api
    labels:
      app: topological-inventory
  spec:
    ports:
    - name: topological-inventory-ingress-api
      port: 3000
      targetPort: 3000
    selector:
      name: topological-inventory-ingress-api
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: topological-inventory-ingress-api
    labels:
      app: topological-inventory
  spec:
    replicas: 1
    selector:
      name: topological-inventory-ingress-api
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: '3000'
          prometheus.io/scrape: 'true'
        name: topological-inventory-ingress-api
        labels:
          name: topological-inventory-ingress-api
          app: topological-inventory
      spec:
        containers:
        - name: topological-inventory-ingress-api
          image: ${IMAGE_NAMESPACE}/topological-inventory-ingress-api:latest
          ports:
          - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
          env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: topological-inventory-api-secrets
                key: secret-key
          - name: QUEUE_HOST
            value: ${KAFKA_BOOTSTRAP_HOST}
          - name: QUEUE_PORT
            value: ${KAFKA_BOOTSTRAP_PORT}
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 500Mi
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - topological-inventory-ingress-api
          from:
            kind: ImageStreamTag
            name: topological-inventory-ingress-api:latest
            namespace: ${IMAGE_NAMESPACE}
parameters:
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: Namespace which contains the image stream to pull from
  value: buildfactory
- name: KAFKA_BOOTSTRAP_HOST
  displayName: Message Queue Hostname
  description: Hostname which will be used to contact the message queue.
  value: mq-kafka
- name: KAFKA_BOOTSTRAP_PORT
  displayName: Message Queue Port
  description: Port which will be used to contact the message queue.
  value: "29092"
